language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pylama
  - pip install -e .
script:
  - python -m compileall custom_components/chargeamps
  - pylama custom_components/chargeamps
notifications:
  email: false
