name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build venv
        run: python -m venv .venv
      - name: Install dependencies
        run: .venv/bin/pip3 install isort black pylama
      - name: isort
        run: .venv/bin/isort --check custom_components/chargeamps
      - name: black
        run: .venv/bin/black --check custom_components/chargeamps
      - name: pylama
        run: .venv/bin/pylama custom_components/chargeamps
